### ISSUE TITLE
step3 error: TypeError: registration_ransac_based_on_feature_matching(): incompatible function arguments.

### ISSUE THREAD

**Issue by Agzieeee** [gitouni/Targetless-LiDAR-camera-calibration#9]
When I finishing step2, I run multiway_reg.py then this comes. 
![image](https://github.com/user-attachments/assets/81e7aac7-7219-46c6-a5a8-8df885705be7)
Would somebody please help me, thanks.

**Comment by gitouni** [comment]
I guess it is caused by the incompatible input of ransac registration.

**Comment by Agzieeee** [comment]
haha, thanks. After I posed this issue, I find there has a closed issue about step3, so I install open3d 0.15.2 and it runs correctly which I formerly used 0.18.0. But in step4 I also encountered a error. If I couldn't solve, would me pose another issue.

**Comment by Agzieeee** [comment]
haha, thanks. After I posed this issue, I find there has a closed issue about step3, so I install open3d 0.15.2 and it runs correctly which I formerly used 0.18.0. But in step4 I also encountered a error. If I couldn't solve, would me pose another issue.

**Comment by gitouni** [comment]
> haha, thanks. After I posed this issue, I find there has a closed issue about step3, so I install open3d 0.15.2 and it runs correctly which I formerly used 0.18.0. But in step4 I also encountered a error. If I couldn't solve, would me pose another issue.

sure
